# Write your query or mutation here
query GetUserWorkflows($publicKey: String!,$status: String!, $resourceIds: [String]!) {
  getUserWorkflows(
    publicKey: $publicKey
    status: $status
    resourceIds: $resourceIds
    #
  )
}